name: Deploy to EC2

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Create SSH Directory
        run: mkdir -p ~/.ssh

      - name: Write SSH Key to id_rsa
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Convert Private Key to PEM (if needed)
        run: |
          if file ~/.ssh/id_rsa | grep -q 'PEM RSA'; then
            echo "Already in PEM format"
          else
            ssh-keygen -p -m PEM -f ~/.ssh/id_rsa -N ''  # Convert key without changing the passphrase
          fi

      - name: Clear known hosts
        run: rm -f ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_rsa -vvv -o StrictHostKeyChecking=no" ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.EC2_DEPLOY_DIR }}
          ssh -i ~/.ssh/id_rsa -vvv ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ${{ secrets.EC2_DEPLOY_DIR }}
            git pull origin main
            npm install
            npm run build
            pm2 restart all
          EOF
